image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-order.jar &

build_script:
  - chmod +x OrderingCard/driver/win/chromedriver.exe
  - ./gradlew test --info